---
title: "Test KM plot from survminer"
output: html_document
---




```{r setup_knitr, include = FALSE, cache = FALSE}
### Packages to compile rmarkdown
library(knitr)
library(rmarkdown)
### Packages for nice tables
library(kableExtra)


font_size <- 11
cache <- 0


knitr::opts_chunk$set(cache = cache, cache.comments = FALSE, echo = TRUE, warning = FALSE, message = FALSE, error = FALSE, fig.width = 6, fig.height = 5, fig.align = "center")




```




```{r library, results="hide"}

### Packages for data manipulations
library(tidyverse)
library(plyr) # rbind.fill
library(limma) # strsplit2

### Packages for plotting
library(cowplot)
library(RColorBrewer) # brewer.pal
library(ggbeeswarm)

### Packages for survival analysis 
library(gClinBiomarker)
library(survival)
library(survminer)
library(forestplot)


library(devtools)


```


```{r load_data}

### For now I use GOYA data but this has to be replaced with a test data that can be made publically available 
### This data should be loaded from data/


data_goya <- readRDS("/Users/nowickm2/Workspace/GOYA_GALLIUM_FCGR/tmp/data_goya.RDS")
data <- data_goya

variable_names <- readRDS("/Users/nowickm2/Workspace/GOYA_GALLIUM_FCGR/tmp/variable_names.RDS")


```



```{r load_package}

devtools::load_all()


```






```{r}


data <- data_goya

tte_var <- "PFS"
censor_var <- "PFS_Censor"
subgroup_var <- "Cell_Of_Origin"

colors = NULL

variable_names = NULL

title = NULL
subtitle = NULL
tag = NULL


break.time.by = NULL
max_tte = NULL


risk.table = TRUE

conf.int = FALSE



title.size = 12

legend.position = c(0.03, 0.03)
legend.justification = c(0, 0)

fontsize = 3.5
rel_heights = c(5, 1)

background_grid_major = "none"



### Keep non-missing data

data <- data[!is.na(data[, tte_var]) & !is.na(data[, censor_var]), ]



### Some checks


variable_names <- format_variable_names(data = data, variable_names = variable_names)

xlab <- variable_names[tte_var]



colors <- format_colors(levels = levels(data[, subgroup_var]), colors = colors)


### Because colors are taken in a row from the beginning of the vector to have consistent coloring we have to remove colors for the levels with zero counts. For the ggsurvplot function and in ggplot adjustment colors cannot have names. Otherwise, it does not work. 

tbl <- table(data[, subgroup_var])

colors <- colors[tbl != 0]

colors <- as.character(colors)

## Removed unused levels from the data too

data[, subgroup_var] <- factor(data[, subgroup_var])


### The default is to have about 10 breaks

if(is.null(break.time.by)){
  
  max_tte_tmp <- max(data[, tte_var], na.rm = TRUE) / 10
  
  decimial_nr <- round(log10(max_tte_tmp))
  
  break.time.by <- round(max_tte_tmp / 10^decimial_nr) * 10^decimial_nr
  
}


### To make sure that no data is cut off the range of the plot, extend the x-axis

if(is.null(max_tte)){
  max_tte <- max(data[, tte_var], na.rm = TRUE)
  max_tte <- ceiling(max_tte / break.time.by) * break.time.by
}else{
  max_tte <- ceiling(max_tte / break.time.by) * break.time.by
}




### Define the model formula
f <- as.formula(paste0("Surv(", tte_var, ",", censor_var,") ~ ", subgroup_var))

### Fit the model
fit <- survival::survfit(f, data)

## Fix a bug. Otherwise, it does not work!!! 
fit$call$formula <- f


### Generate Kaplan-Meier plot

## palette must be a non-named vector. Otherwise, it does not work. For each subplot has to have unique values. If a level has zero counts, it is not plotted. Because colors are taken in a row from the beginning of the vector to have consistent coloring we have to remove colors for the levels with zero counts.

ggpl <- survminer::ggsurvplot(fit, data = data, palette = colors, linetype = 1, conf.int = conf.int, risk.table = risk.table, ggtheme = theme_classic(), xlab = xlab, break.time.by = break.time.by, xlim = c(0, max_tte), fontsize = fontsize) 


ggpl



ggpl$plot
ggpl$table



### Customize the plot
suppressMessages(ggpl_plot <- ggpl$plot +
  labs(title = title, subtitle = subtitle, tag = tag) +
  theme(plot.title = element_text(size = title.size, face = "bold"),
    legend.position = legend.position,
    legend.justification = legend.justification,
    legend.title = element_blank(), 
    legend.background = element_rect(fill = NA),
    plot.tag.position = "top",
    plot.tag = element_text(size = title.size, face = "plain")) +
  scale_color_manual(labels = levels(data[, subgroup_var]), values = colors) +
  scale_fill_manual(labels = levels(data[, subgroup_var]), values = colors) +
  coord_cartesian(xlim = c(0, max_tte)) +
  background_grid(major = background_grid_major, minor = "none", size.major = 0.15))

ggpl_plot


suppressMessages(ggpl_table <- ggpl$table +
  theme(plot.title = element_text(size = title.size),
    axis.title = element_blank(), 
    axis.text.x = element_blank(),
    axis.ticks = element_blank(), 
    axis.line=element_blank()) +
  scale_y_discrete(labels = rev(levels(data[, subgroup_var]))) +
  coord_cartesian(xlim = c(0, max_tte)))

ggpl_table


ggpl_new <- cowplot::plot_grid(ggpl_plot, ggpl_table, ncol = 1, align = 'v', axis = 'l', rel_heights = rel_heights)

ggpl_new







```









































