
###############################################################################
### Set class unions
###############################################################################

### To allow caption = NULL
setClassUnion("characterNULL", c("character", "NULL"))

### To allow header = NULL
setClassUnion("integernumericNULL", c("integer", "numeric", "NULL"))


###############################################################################
### Bclass class which is a virtual class
###############################################################################


#' Bclass object
#' 
#' A Bclass object is a container for results generated by the wrappers.
#' 
#' @details 
#' 
#' Methods:
#' 
#' \itemize{ 
#' \item \code{bresults(x)}: Get a data frame with results. 
#' \item \code{boutput(x)}: Get a data frame with output that is dispalyed with kable.
#' \item \code{bcaption(x)}: Get a string with caption that is displayed with kable.
#' \item \code{bheader(x)}: Get a vector with header that is displayed with kable.
#' \item \code{bkable(x)}: Display output with kable.
#' \item \code{bforest(x)}: Generate a forest plot. 
#' }
#' 
#' Inheriting classes:
#' 
#' \itemize{
#' \item \code{Bclass}
#' }
#' 
#' 
#' @param object,x Bclass object.
#' @param value New values.
#'   
#' @slot results Data frame with results.
#' @slot output Data frame with output that is dispalyed with kable.
#' @slot caption String with caption that is displayed in the table.
#' @slot header Names integer vector with header that is displayed in the table.
#'   
#' @author Malgorzata Nowicka
Bclass <- setClass("Bclass", 
  slots = c(results = "data.frame", 
    output = "data.frame",
    caption = "characterNULL",
    header = "integernumericNULL"),
  prototype = list(results = data.frame(), 
    output = data.frame(),
    caption = NULL,
    header = NULL))



# --------------------------------------------------------------------------
# Object validation
# --------------------------------------------------------------------------


setValidity("Bclass", function(object){
  # It has to return TRUE when valid object!
  
  if(nrow(object@results) == nrow(object@output)){
    out <- TRUE
  }else{
    return(paste0("Different number of rows for 'results' and 'output'!"))
  }
  
  if(!is.null(object@header)){
    if(sum(object@header) == ncol(object@output)){
      out <- TRUE
    }else{
      return(paste0("Sum of values in 'header' must be equal to the number of columns in 'output'!"))
    }
  }
  
  return(out)
  
})



################################################################################
### Generic for the show method
################################################################################


#' @rdname Bclass-class
#' @export
setGeneric("bkable", function(x, ...) standardGeneric("bkable"))


#' @rdname Bclass-class
#' @export
setGeneric("bforest", function(x, ...) standardGeneric("bforest"))


################################################################################
### Accessor methods
################################################################################


### results


#' @rdname Bclass-class
#' @export
setGeneric("bresults", function(x, ...) standardGeneric("bresults"))


#' @rdname Bclass-class
#' @export
setMethod("bresults", "Bclass", function(x) x@results )


#' @rdname Bclass-class
#' @export
setMethod("bresults", "NULL", function(x) NULL )



#' @rdname Bclass-class
#' @export
setGeneric("bresults<-", function(x, value) standardGeneric("bresults<-"))


#' @rdname Bclass-class
#' @export
setMethod("bresults<-", "Bclass", function(x, value){
  
  Bclass(results = value, output = boutput(x), caption = bcaption(x), header = bheader(x))
  
})




### output


#' @rdname Bclass-class
#' @export
setGeneric("boutput", function(x, ...) standardGeneric("boutput"))


#' @rdname Bclass-class
#' @export
setMethod("boutput", "Bclass", function(x) x@output )


#' @rdname Bclass-class
#' @export
setMethod("boutput", "NULL", function(x) NULL )



#' @rdname Bclass-class
#' @export
setGeneric("boutput<-", function(x, value) standardGeneric("boutput<-"))


#' @rdname Bclass-class
#' @export
setMethod("boutput<-", "Bclass", function(x, value){
  
  Bclass(results = bresults(x), output = value, caption = bcaption(x), header = bheader(x))
  
})





### caption


#' @rdname Bclass-class
#' @export
setGeneric("bcaption", function(x, ...) standardGeneric("bcaption"))


#' @rdname Bclass-class
#' @export
setMethod("bcaption", "Bclass", function(x) x@caption )


#' @rdname Bclass-class
#' @export
setMethod("bcaption", "NULL", function(x) NULL )


#' @rdname Bclass-class
#' @export
setGeneric("bcaption<-", function(x, value) standardGeneric("bcaption<-"))


#' @rdname Bclass-class
#' @export
setMethod("bcaption<-", "Bclass", function(x, value){
  
  Bclass(results = bresults(x), output = boutput(x), caption = value, header = bheader(x))
  
})


### header


#' @rdname Bclass-class
#' @export
setGeneric("bheader", function(x, ...) standardGeneric("bheader"))


#' @rdname Bclass-class
#' @export
setMethod("bheader", "Bclass", function(x) x@header )


#' @rdname Bclass-class
#' @export
setMethod("bheader", "NULL", function(x) NULL )


#' @rdname Bclass-class
#' @export
setGeneric("bheader<-", function(x, value) standardGeneric("bheader<-"))


#' @rdname Bclass-class
#' @export
setMethod("bheader<-", "Bclass", function(x, value){
  
  Bclass(results = bresults(x), output = boutput(x), caption = bcaption(x), header = value)
  
})
























