

###############################################################################
### BiomarkerClass class which is a virtual class
###############################################################################

#' BiomarkerClass object
#' 
#' A BiomarkerClass object is a container for results generated by the wrappers.
#' 
#' @details 
#' 
#' Methods:
#' 
#' \itemize{ 
#' \item \code{BiomarkerResults(x)}: Get a data frame with results. 
#' \item \code{BiomarkerOutput(x)}: Get a data frame with output that is dispalyed with kable.
#' \item \code{BiomarkerCaption(x)}: Get a string with caption that is displayed with kable.
#' \item \code{BiomarkerKable(x)}: Display output with kable.
#' }
#' 
#' Inheriting classes:
#' 
#' \itemize{
#' \item \code{BiomarkerCoreCoxRegression}
#' }
#' 
#' 
#' @param object,x BiomarkerClass object.
#' @param value New values.
#'   
#' @slot results Data frame with results.
#' @slot output Data frame with output that is dispalyed with kable.
#' @slot caption String with caption that is displayed in the table.
#'   
#' @author Malgorzata Nowicka
BiomarkerClass <- setClass("BiomarkerClass", 
  slots = c(results = "data.frame", 
    output = "data.frame",
    caption = "character"))



# --------------------------------------------------------------------------
# Object validation
# --------------------------------------------------------------------------


setValidity("BiomarkerClass", function(object){
  # It has to return TRUE when valid object!
  
  if(nrow(object@results) == nrow(object@output)){
    out <- TRUE
  }else{
    return(paste0("Different number of rows for 'results' and 'output'!"))
  }
  
  return(out)
  
})



################################################################################
### Generic for the show method
################################################################################


#' @rdname BiomarkerClass-class
#' @export
setGeneric("BiomarkerKable", function(x, ...) standardGeneric("BiomarkerKable"))



################################################################################
### Accessor methods
################################################################################


#' @rdname BiomarkerClass-class
#' @export
setGeneric("BiomarkerResults", function(x, ...) standardGeneric("BiomarkerResults"))


#' @rdname BiomarkerClass-class
#' @export
setMethod("BiomarkerResults", "BiomarkerClass", function(x) x@results )


#' @rdname BiomarkerClass-class
#' @export
setGeneric("BiomarkerResults<-", function(x, value) standardGeneric("BiomarkerResults<-"))


#' @rdname BiomarkerClass-class
#' @export
setMethod("BiomarkerResults<-", "BiomarkerClass", function(x, value){
  
  BiomarkerCoreCoxRegression(results = value, output = BiomarkerOutput(x), caption = BiomarkerCaption(x))
  
})







#' @rdname BiomarkerClass-class
#' @export
setGeneric("BiomarkerOutput", function(x, ...) standardGeneric("BiomarkerOutput"))


#' @rdname BiomarkerClass-class
#' @export
setMethod("BiomarkerOutput", "BiomarkerClass", function(x) x@output )



#' @rdname BiomarkerClass-class
#' @export
setGeneric("BiomarkerOutput<-", function(x, value) standardGeneric("BiomarkerOutput<-"))


#' @rdname BiomarkerClass-class
#' @export
setMethod("BiomarkerOutput<-", "BiomarkerClass", function(x, value){
  
  BiomarkerCoreCoxRegression(results = BiomarkerResults(x), output = value, caption = BiomarkerCaption(x))
  
})





#' @rdname BiomarkerClass-class
#' @export
setGeneric("BiomarkerCaption", function(x, ...) standardGeneric("BiomarkerCaption"))


#' @rdname BiomarkerClass-class
#' @export
setMethod("BiomarkerCaption", "BiomarkerClass", function(x) x@caption )



#' @rdname BiomarkerClass-class
#' @export
setGeneric("BiomarkerCaption<-", function(x, value) standardGeneric("BiomarkerCaption<-"))


#' @rdname BiomarkerClass-class
#' @export
setMethod("BiomarkerCaption<-", "BiomarkerClass", function(x, value){
  
  BiomarkerCoreCoxRegression(results = BiomarkerResults(x), output = BiomarkerOutput(x), caption = value)
  
})



























