
###############################################################################
### Set class unions
###############################################################################

### To allow caption = NULL
setClassUnion("characterNULL", c("character", "NULL"))

### To allow header = NULL
setClassUnion("integernumericNULL", c("integer", "numeric", "NULL"))


###############################################################################
### Bclass class which is a virtual class
###############################################################################


#' Bclass object
#' 
#' A Bclass object is a container for results generated by the wrappers.
#' 
#' @details 
#' 
#' Methods:
#' 
#' \itemize{ 
#' \item \code{Bresults(x)}: Get a data frame with results. 
#' \item \code{Boutput(x)}: Get a data frame with output that is dispalyed with kable.
#' \item \code{Bcaption(x)}: Get a string with caption that is displayed with kable.
#' \item \code{Bheader(x)}: Get a vector with header that is displayed with kable.
#' \item \code{Bkable(x)}: Display output with kable.
#' }
#' 
#' Inheriting classes:
#' 
#' \itemize{
#' \item \code{Bclass}
#' }
#' 
#' 
#' @param object,x Bclass object.
#' @param value New values.
#'   
#' @slot results Data frame with results.
#' @slot output Data frame with output that is dispalyed with kable.
#' @slot caption String with caption that is displayed in the table.
#' @slot header Names integer vector with header that is displayed in the table.
#'   
#' @author Malgorzata Nowicka
Bclass <- setClass("Bclass", 
  slots = c(results = "data.frame", 
    output = "data.frame",
    caption = "characterNULL",
    header = "integernumericNULL"),
  prototype = list(results = data.frame(), 
    output = data.frame(),
    caption = NULL,
    header = NULL))



# --------------------------------------------------------------------------
# Object validation
# --------------------------------------------------------------------------


setValidity("Bclass", function(object){
  # It has to return TRUE when valid object!
  
  if(nrow(object@results) == nrow(object@output)){
    out <- TRUE
  }else{
    return(paste0("Different number of rows for 'results' and 'output'!"))
  }
  
  if(!is.null(object@header)){
    if(sum(object@header) == ncol(object@output)){
      out <- TRUE
    }else{
      return(paste0("Sum of values in 'header' must be equal to the number of columns in 'output'!"))
    }
  }
  
  return(out)
  
})



################################################################################
### Generic for the show method
################################################################################


#' @rdname Bclass-class
#' @export
setGeneric("Bkable", function(x, ...) standardGeneric("Bkable"))


#' @rdname Bclass-class
#' @export
setGeneric("Bforest", function(x, ...) standardGeneric("Bforest"))


################################################################################
### Accessor methods
################################################################################


### results


#' @rdname Bclass-class
#' @export
setGeneric("Bresults", function(x, ...) standardGeneric("Bresults"))


#' @rdname Bclass-class
#' @export
setMethod("Bresults", "Bclass", function(x) x@results )


#' @rdname Bclass-class
#' @export
setMethod("Bresults", "NULL", function(x) NULL )



#' @rdname Bclass-class
#' @export
setGeneric("Bresults<-", function(x, value) standardGeneric("Bresults<-"))


#' @rdname Bclass-class
#' @export
setMethod("Bresults<-", "Bclass", function(x, value){
  
  Bclass(results = value, output = Boutput(x), caption = Bcaption(x), header = Bheader(x))
  
})




### output


#' @rdname Bclass-class
#' @export
setGeneric("Boutput", function(x, ...) standardGeneric("Boutput"))


#' @rdname Bclass-class
#' @export
setMethod("Boutput", "Bclass", function(x) x@output )


#' @rdname Bclass-class
#' @export
setMethod("Boutput", "NULL", function(x) NULL )



#' @rdname Bclass-class
#' @export
setGeneric("Boutput<-", function(x, value) standardGeneric("Boutput<-"))


#' @rdname Bclass-class
#' @export
setMethod("Boutput<-", "Bclass", function(x, value){
  
  Bclass(results = Bresults(x), output = value, caption = Bcaption(x), header = Bheader(x))
  
})





### caption


#' @rdname Bclass-class
#' @export
setGeneric("Bcaption", function(x, ...) standardGeneric("Bcaption"))


#' @rdname Bclass-class
#' @export
setMethod("Bcaption", "Bclass", function(x) x@caption )


#' @rdname Bclass-class
#' @export
setMethod("Bcaption", "NULL", function(x) NULL )


#' @rdname Bclass-class
#' @export
setGeneric("Bcaption<-", function(x, value) standardGeneric("Bcaption<-"))


#' @rdname Bclass-class
#' @export
setMethod("Bcaption<-", "Bclass", function(x, value){
  
  Bclass(results = Bresults(x), output = Boutput(x), caption = value, header = Bheader(x))
  
})


### header


#' @rdname Bclass-class
#' @export
setGeneric("Bheader", function(x, ...) standardGeneric("Bheader"))


#' @rdname Bclass-class
#' @export
setMethod("Bheader", "Bclass", function(x) x@header )


#' @rdname Bclass-class
#' @export
setMethod("Bheader", "NULL", function(x) NULL )


#' @rdname Bclass-class
#' @export
setGeneric("Bheader<-", function(x, value) standardGeneric("Bheader<-"))


#' @rdname Bclass-class
#' @export
setMethod("Bheader<-", "Bclass", function(x, value){
  
  Bclass(results = Bresults(x), output = Boutput(x), caption = Bcaption(x), header = value)
  
})
























